module.exports = {
  preset: 'react-native',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.test.js'],
  setupFiles: ['<rootDir>/jest.setup.js'],
  collectCoverageFrom: [
    'src/utils/**/*.js',
    'src/hooks/**/*.js',
    'src/constants/**/*.js',
    'src/navigation/**/*.js',
    'src/contexts/clientDataUtils.js',
    'src/config/runtimeConfig.js',
    'src/services/httpClient.js',
    'src/services/syncflowHttp.js',
    'src/services/authSessionStorage.js',
    'src/services/mockApi.js',
    'src/services/api/**/*.js',
    '!src/services/api/**/*.test.js',
    '!src/test/**',
  ],
  transformIgnorePatterns: [
    'node_modules/(?!(react-native|@react-native|expo(nent)?|@expo|expo-.*|@react-navigation)/)',
  ],
};
